### ISSUE TITLE
Backspace not working on android

### ISSUE THREAD

**Issue by Harshiv-Patel** [kba/jcurses#1]
I have built jcurses libraries for Android Lollipop 5.1.1(CPU: armv7l) , from this repo, in Termux android app. I face one problem that, in Widgets like TextField and TextArea , the backspace button does not work.

So I checked the output of terminal, it sends integer 127 for backspace.
so I modified ToolKit.c for octal value of 127 i.e. (0177) to receive backspace key events. But it doesn't seem to work.
When I hit ctrl+h , one character is erased from screen. Can you please suggest me how to modify  it to work correctly with android ?

**Comment by kba** [comment]
Sorry, I haven't used the lib in 4+ years and I merely fixed things so it would build. Maybe @jwoehr who wrote the library (kudos!) can help? You could also check http://sourceforge.net/projects/javacurses, it has been updated since and there is a discussion board over there.

**Comment by Harshiv-Patel** [comment]
As issue was related to bad xterm file, it is not connected to Jcurses library. I had to modify my xterm-256color file(decompile-edit-compile) to include proper backspace code "kbs=\177" and it works.

**Comment by kba** [comment]
Great, thanks for following up!

**Comment by jwoehr** [comment]
@kba Thanks for your kind words. I did not write JCurses, I merely did some maintenance on it and watched the bug list for a couple of years several years back, maybe 7 years ago or more.
